### ISSUE TITLE
Calorie Negation utilizes new getRandom() methods for each new exercise type

### ISSUE THREAD

**Issue by awrigh36** [GymRatTrax/GymRatTrax-Scheduler#54]
Bug fix request to allow getRandom() for strength workouts. Currently getRandom() works only for Cardio Workouts, trying to call ExerciseName.Legs.getRandom(), for instance, raises a compilation error.

**Comment by chrisstonedev** [comment]
This isn't so much as a bug yet as it is incomplete code. The ExerciseName values have been separated into different sets. In code that I will be checking in tonight, Calorie Negation will show exercises from all categories. The problem is that ExerciseName currently cannot hold all exercise names, so in order to make Calorie Negation conform to the new standard, the ExerciseName array became an ExerciseName.Cardio array as a temporary fix, which explains why ExerciseName.Legs.getRandom() will not return a value that is acceptable for the existing array. Again, this will definitely be fixed tonight.

**Comment by chrisstonedev** [comment]
Completed. Calorie Negation will still be improved time permitting before the beta build, but it is pulling in exercises of various types again and adding is working successfully.
